In [1]:
import numpy as np
import csv
import scipy.io
!pwd

/home/yousof/RideCellAssignment/scripts


In [2]:
csvFile = "res.txt"

In [3]:
# read the csv file
vectors = []
with open(csvFile) as f:
    csvReader = csv.reader(f, delimiter = ',')
    for row in csvReader:
        vectors.append([float(e) for e in row])
        
print(type (vectors[0][0]),vectors[0])

<class 'float'> [-0.0135694, 0.0484322, -0.998734, 0.985475, -0.121977, 0.118152, -1.69102]


In [4]:
vecs = np.array(vectors,dtype = np.float32)
print(vecs.shape)

(35, 7)


In [5]:
noramlFromCam = vecs[:,:3]
noramlFromPC = vecs[:,3:6]
print(noramlFromCam[0,:])
print(noramlFromPC[0,:])

[-0.0135694  0.0484322 -0.998734 ]
[ 0.985475 -0.121977  0.118152]


In [8]:
A = np.empty((3,0), dtype=np.float32)
B = np.empty((3,0), dtype=np.float32)
for idx in range(vecs.shape[0]):
    v_c = noramlFromCam[idx,:]
    v_l = noramlFromPC[idx,:]
    if (v_l[0]>0):
        v_l = v_l * (-1)
    v_c = v_c / np.linalg.norm(v_c)
    v_l = v_l /  np.linalg.norm(v_l)
    expanded_c = np.expand_dims(v_c,0)
    expanded_l = np.expand_dims(v_l,0)
    A = np.concatenate((A,expanded_c.reshape(3,1)),axis=1)
    B = np.concatenate((B,expanded_l.reshape(3,1)),axis=1)
    
u,s,vt = np.linalg.svd(np.matmul(B,A.transpose()))
mid = np.identity(3,dtype=np.float32)
mid[2,2] = np.linalg.det(np.matmul(u,vt))
R = np.matmul(np.matmul(vt.transpose(),mid),u.transpose())
print("Rotation Matrix from Lidar to CAmera frame:")
print(R)

Rotation Matrix from Lidar to CAmera frame:
[[-0.08604091 -0.9962046   0.01316683]
 [ 0.07531615 -0.01968187 -0.99696535]
 [ 0.9934407  -0.08478814  0.07672376]]
